package main

// main.go — Generated by IoTMaker IDE · Echo Hello World template.
// Run:  go mod tidy && go run .
// Then: open http://localhost:{{.Port}}

import (
	"html/template"
	"io"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// renderer implements echo.Renderer using Go's html/template package.
// It loads all *.html files from the templates/ directory.
type renderer struct {
	t *template.Template
}

func (r *renderer) Render(w io.Writer, name string, data any, c echo.Context) error {
	return r.t.ExecuteTemplate(w, name, data)
}

func main() {
	e := echo.New()
	e.HideBanner = true

	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Register HTML template renderer.
	e.Renderer = &renderer{
		t: template.Must(template.ParseGlob("templates/*.html")),
	}

	// GET / — renders templates/index.html with the configured greeting.
	e.GET("/", func(c echo.Context) error {
		return c.Render(http.StatusOK, "index.html", map[string]any{
			"Message": "{{.Message}}",
			"Port":    "{{.Port}}",
		})
	})

	// Start the server on the configured port.
	e.Logger.Fatal(e.Start(":{{.Port}}"))
}
